### ISSUE TITLE
The parameter "username" in ChatHub causes JsonException

### ISSUE THREAD

**Issue by git-Charlie** [aspnet/AspNetCore.Docs#12878]
sdk : 3.0.100-preview6-012264
[Enter feedback here]
##  Details
```
 public class ChatHub : Hub
    {
        public async Task NewMessage(string username, string message)
        {
            await Clients.All.SendAsync("messageReceived", username, message);
        }
    }
```
 **Causes JsonException**

```
System.IO.InvalidDataException: Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked. ---> System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $ | LineNumber: 0 | BytePositionInLine: 13.
   at System.Text.Json.ThrowHelper.ThowJsonException(String message, Utf8JsonReader& reader, String path)
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType, Utf8JsonReader& reader, String path)
   at System.Text.Json.Serialization.JsonPropertyInfoNotNullable`3.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.JsonSerializer.HandleValue(JsonTokenType tokenType, JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.Serialization.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.Serialization.JsonSerializer.ReadValueCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.Serialization.JsonSerializer.ReadValueCore(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonSerializer.ReadValue(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindTypes(Utf8JsonReader& reader, IReadOnlyList`1 paramTypes)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindTypes(Utf8JsonReader& reader, IReadOnlyList`1 paramTypes)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.ParseMessage(ReadOnlySequence`1 input, IInvocationBinder binder) 
```

## Solution

Change 

```
 public async Task NewMessage(string username, string message)
```
TO 
```
 public async Task NewMessage(long username, string message)
```

because message json look like this:
```
{"arguments":[1560504537611,"ok"],"target":"newMessage","type":1}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47557f89-3a14-1139-0074-38d931b35faf
* Version Independent ID: 1cee43b4-b672-e480-3e26-72e08a6c2d77
* Content: [Use ASP.NET Core SignalR with TypeScript and Webpack](https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-typescript-webpack?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/signalr-typescript-webpack.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/signalr-typescript-webpack.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @ssougnez
* Microsoft Alias: **bradyg**

**Comment by BrennanConroy** [comment]
This is expected. Starting with preview5 the default Json implementation is now System.Text.Json instead of Newtonsoft.Json. Converting a number to a string on deserialization is a feature that is not in System.Text.Json which is why you're seeing an error.

One way to fix this is by what you've done, change the expected type to match the incoming type. If you're not happy with that then you can switch back to Newtonsoft.Json as the underlying protocol. See https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis/#user-content-integration-with-signalr

If you'd like to read more about the new Json library, read the blog post https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis

**Comment by BrennanConroy** [comment]
Oh, didn't realize you were talking about `ChatHub` in the doc 😄 

We'll fix that up, thanks for noticing.

**Comment by git-Charlie** [comment]
> This is expected. Starting with preview5 the default Json implementation is now System.Text.Json instead of Newtonsoft.Json. Converting a number to a string on deserialization is a feature that is not in System.Text.Json which is why you're seeing an error.
> 
> One way to fix this is by what you've done, change the expected type to match the incoming type. If you're not happy with that then you can switch back to Newtonsoft.Json as the underlying protocol. See https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis/#user-content-integration-with-signalr
> 
> If you'd like to read more about the new Json library, read the blog post https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis

Thank you for your reply. I am still a rookie who relies on doc and example to learn.
