### ISSUE TITLE
GrPC invalid http/2 connection preface

### ISSUE THREAD

**Issue by hooseinsaid** [aspnet/AspNetCore.Docs#13111]
Microsoft.AspNetCore.Server.Kestrel: Information: Connection id "0HLO001722806": HTTP/2 connection error.

Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2ConnectionErrorException: HTTP/2 connection error (PROTOCOL_ERROR): Invalid HTTP/2 connection preface.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ParsePreface(ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.TryReadPrefaceAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
Microsoft.AspNetCore.Server.Kestrel: Information: Connection id "0HLO001722807": HTTP/2 connection error.

Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2ConnectionErrorException: HTTP/2 connection error (PROTOCOL_ERROR): Invalid HTTP/2 connection preface.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ParsePreface(ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.TryReadPrefaceAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
Microsoft.AspNetCore.Server.Kestrel: Information: Connection id "0HLO001722808": HTTP/2 connection error.

Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2ConnectionErrorException: HTTP/2 connection error (PROTOCOL_ERROR): Invalid HTTP/2 connection preface.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ParsePreface(ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.TryReadPrefaceAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
Microsoft.Hosting.Lifetime: Information: Application is shutting down...
EventSource Error: ERROR: Exception during construction of EventSource Microsoft-System-Net-Primitives: Incorrect function.
The program '[15348] GrPC.exe: Program Trace' has exited with code 0 (0x0).
The program '[15348] GrPC.exe' has exited with code -1073741510 (0xc000013a).

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select the **Content feedback** issue.
![image](https://user-images.githubusercontent.com/3605364/52735418-b23f2680-2f6b-11e9-81c5-ec0105e55d00.png)
