### ISSUE TITLE
Error when attempting to scaffold Courses

### ISSUE THREAD

**Issue by tg73** [aspnet/AspNetCore.Docs#14044]
When attempting to scaffold Courses as instructed [here](https://docs.microsoft.com/en-gb/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-3.0&tabs=visual-studio-code#scaffold-course-pages), I get the following error in VS:

![image](https://user-images.githubusercontent.com/1101693/63789246-e3bb8600-c8ee-11e9-85f3-4d03d0f6996b.png)

Using `dotnet` I get:

```console
Building project ...
Finding the generator 'razorpage'...
Running the generator 'razorpage'...
Attempting to compile the application in memory.
Could not get the reflection type for DbContext : ContosoUniversity.Data.SchoolContext
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
```

Also logged here: https://github.com/aspnet/Scaffolding/issues/1055

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0026f69-7e5d-0d3e-5586-16ecc0656ff0
* Version Independent ID: 3cb264da-2ff1-1256-572f-aa4ebca6e255
* Content: [Razor Pages with EF Core in ASP.NET Core - Read Related Data - 6 of 8](https://docs.microsoft.com/en-gb/aspnet/core/data/ef-rp/read-related-data?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/data/ef-rp/read-related-data.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/data/ef-rp/read-related-data.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @tdykstra
* Microsoft Alias: **riande**

**Comment by tg73** [comment]
I had forgotten that I had applied a VS analyzer code change suggestion to convert a `switch` _statement_ to a `switch` _expression_ in `Pages/Students/Index.cshtml.cs`. The code exactly as per the tutorials does not have this problem. I have updated aspnet/Scaffolding#1055 accordingly. Closing this issue.
