### ISSUE TITLE
aspnet-codegenerator cannot generate with error

### ISSUE THREAD

**Issue by TangMonk** [aspnet/AspNetCore.Docs#14743]
```
$ dotnet aspnet-codegenerator razorpage -m Movie -dc RazorPagesMovieContext -udl -outDir Pages/Movies --referenceScriptLibraries

Building project ...
Finding the generator 'razorpage'...
Running the generator 'razorpage'...
Attempting to compile the application in memory.
Attempting to figure out the EntityFramework metadata for the model and DbContext: 'Movie'
Unable to create an object of type 'RazorPagesMovieContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728 StackTrace:
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.&lt;&gt;c__DisplayClass13_3.&lt;FindContextTypes&gt;b__13()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.DbContextActivator.CreateInstance(Type contextType, Assembly startupAssembly, IOperationReportHandler reportHandler)
   at Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.EntityFrameworkModelProcessor.TryCreateContextUsingAppCode(Type dbContextType, Type startupType)

No parameterless constructor defined for type 'test_webapp.Models.RazorPagesMovieContext'. StackTrace:
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.&lt;&gt;c__DisplayClass13_3.&lt;FindContextTypes&gt;b__13()

No parameterless constructor defined for type 'test_webapp.Models.RazorPagesMovieContext'.
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.&lt;BuildCommandLine&gt;b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:09.90
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Add a model to a Razor Pages app in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-3.0&tabs=visual-studio-code#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Looks like you missed a step, maybe adding the DB context.

**Comment by TangMonk** [comment]
my Data/RazorPagesMovieContext.cs:

```
using System;
using Microsoft.EntityFrameworkCore;

namespace test_webapp.Models
{
  public class RazorPagesMovieContext : DbContext
  {
    public RazorPagesMovieContext(DbContextOptions<RazorPagesMovieContext> options)
        : base(options)
    {
    }

    public DbSet<test_webapp.Models.Movie> Movie { get; set; }
  }
}

```

my Models/Movies.cs:

```
using System;
using System.ComponentModel.DataAnnotations;

namespace test_webapp.Models
{
  public class Movie
  {
    public int ID { get; set; }
    public string Title { get; set; }

    [DataType(DataType.Date)]
    public DateTime ReleaseDate { get; set; }
    public string Genre { get; set; }
    public decimal Price { get; set; }
  }
}

```

**Comment by lichengdao** [comment]
have the same problem too.
who can solve it

**Comment by Rick-Anderson** [comment]
You need to follow the instructions. Your namespace is wrong
`namespace test_webapp.Models`
