### ISSUE TITLE
Unable to propagate server context values to the call. Can't find the current HttpContext.

### ISSUE THREAD

**Issue by khteh** [aspnet/AspNetCore.Docs#14903]
```
services.AddGrpcClient<Greeter.GreeterClient>(o => { o.Address = new Uri("http://localhost:5000");})
                    .EnableCallContextPropagation();
IServiceProvider serviceProvider = services.BuildServiceProvider();
Greeter.GreeterClient grpcClient = serviceProvider.GetRequiredService<Greeter.GreeterClient>();
await grpcClient.SayHelloAsync(new HelloRequest() {Name = "ASP.Net Core 3.0"});
```
results in:
```
Unhandled exception. System.InvalidOperationException: Unable to propagate server context values to the call. Can't find the current HttpContext.
   at Grpc.AspNetCore.Server.ClientFactory.ContextPropagationInterceptor.GetServerCallContext()
   at Grpc.AspNetCore.Server.ClientFactory.ContextPropagationInterceptor.ConfigureContext[TRequest,TResponse](ClientInterceptorContext`2 context, CancellationTokenSource& linkedCts)
   at Grpc.AspNetCore.Server.ClientFactory.ContextPropagationInterceptor.AsyncUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, AsyncUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.&lt;AsyncUnaryCall&gt;b__4_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.AsyncUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, AsyncUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at GrpcGreeter.Greeter.GreeterClient.SayHelloAsync(HelloRequest request, CallOptions options) in /usr/src/GRPC/Greeter/src/GrpcClient/obj/Debug/netcoreapp3.0/GreetGrpc.cs:line 99
   at GrpcGreeter.Greeter.GreeterClient.SayHelloAsync(HelloRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in /usr/src/GRPC/Greeter/src/GrpcClient/obj/Debug/netcoreapp3.0/GreetGrpc.cs:line 89
   at GrpcClient.Program.Main(String[] args) in /usr/src/GRPC/Greeter/src/GrpcClient/Program.cs:line 53
   at GrpcClient.Program.&lt;Main&gt;(String[] args)
```
What do I miss?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35f64666-6632-cfca-2c3b-a20ea016f62b
* Version Independent ID: caebee8f-f4aa-17a4-3681-d10c4695e9c0
* Content: [gRPC client factory integration in .NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/clientfactory?view=aspnetcore-3.0)
* Content Source: [aspnetcore/grpc/clientfactory.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/clientfactory.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JamesNK
* Microsoft Alias: **jamesnk**

**Comment by Rick-Anderson** [comment]
The tutorial works. I'm not sure what step you missed. You might try asking on StackOverflow,.
