### ISSUE TITLE
Integration test using WebApplicationFactory<Startup>

### ISSUE THREAD

**Issue by khteh** [aspnet/AspNetCore.Docs#14905]
Is it possible to have an end-to-end GRPC integration test using `WebApplicationFactory<Startup>` like what we did for Restful WebAPI? I tried to do that but doesn't work. Exception:
```
Exception thrown: 'Grpc.Core.RpcException' in System.Private.CoreLib.dll: 'Status(StatusCode=Cancelled, Detail="Error starting gRPC call.")'
   at Grpc.Net.Client.Internal.GrpcCall`2.&lt;GetResponseAsync&gt;d__63.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Web.Api.IntegrationTests.Services.AccountsServiceIntegrationTests.&lt;CanRegisterUserWithValidAccountDetails&gt;d__2.MoveNext() in 
```
What I do in the integration test project:
```
    public class CustomGrpcServerFactory<TStartup> : WebApplicationFactory<Startup>
    {
        public ServiceProvider ServiceProvider {get; private set;}
        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            Environment.SetEnvironmentVariable("ASPNETCORE_ENVIRONMENT", "IntegrationTests");
            string contentRootFull = Path.GetFullPath(Directory.GetCurrentDirectory());
            IConfigurationRoot config = new ConfigurationBuilder()
                .SetBasePath(contentRootFull)
                .AddJsonFile("appsettings.json", false, true)
                .AddJsonFile($"appsettings.Development.json", true, true)
                .AddEnvironmentVariables().Build();
            GrpcConfig grpcConfig = config.GetSection(nameof(GrpcConfig)).Get<GrpcConfig>();
// It doesn't make any difference with or without the following ConfigureKestrel!
            builder.ConfigureKestrel(options =>
            {
                options.Listen(IPAddress.Any, 5000, listenOptions =>
                {
                    listenOptions.Protocols = HttpProtocols.Http2;
                    listenOptions.UseHttps("/tmp/localhost.pfx", "password");
                });
            });
            builder.ConfigureServices(services =>
            {
                // Create a new service provider.
                var serviceProvider = new ServiceCollection()
                    .AddEntityFrameworkInMemoryDatabase().AddLogging()
                    .BuildServiceProvider();
                services.AddGrpcClient<AccountsClient>(new Uri(grpcConfig.Endpoint));
                services.AddGrpcClient<AuthClient>(new Uri(grpcConfig.Endpoint));
<snip>
```
And my Startup.cs:
```
            app.UseEndpoints(endpoints =>
                {
                    endpoints.MapGrpcService<AccountsService>();
                    endpoints.MapGrpcService<AuthService>();
                }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0db2d29c-ebfd-9c79-4b08-61fc5192f3c3
* Version Independent ID: 048d1977-93aa-f28a-60ec-6806dec3f70a
* Content: [Introduction to gRPC on .NET Core](https://docs.microsoft.com/en-us/aspnet/core/grpc/?view=aspnetcore-3.0)
* Content Source: [aspnetcore/grpc/index.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/grpc/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-grpc**
* GitHub Login: @JunTaoLuo
* Microsoft Alias: **johluo**

**Comment by Tratcher** [comment]
@JamesNK

**Comment by tobydaigneault** [comment]
Even if not using WebApplicationFactory<TStartup> has anyone gotten a way to perform integration tests with grpc? Any workaround for this?

I tried multiple things to get an in-process server going but never managed to get a functioning grpc call.

**Comment by JamesNK** [comment]
https://github.com/grpc/grpc-dotnet use to use TestServer for its functional tests.

See: https://github.com/grpc/grpc-dotnet/blob/04c04d4c6070fc6e389abd0d8da9c12919e6ad6d/test/FunctionalTests/Infrastructure/GrpcTestFixture.cs

We'll add a sample of using functional tests at some point - https://github.com/grpc/grpc-dotnet/issues/601

**Comment by JamesNK** [comment]
Sample added today 😄 

https://github.com/grpc/grpc-dotnet/pull/618

**Comment by JamesNK** [comment]
Closing as answered.
