### ISSUE TITLE
Obtaining the DB service from a test causes an error since 3.0

### ISSUE THREAD

**Issue by bluebaroncanada** [aspnet/AspNetCore.Docs#14930]
Before you used to be able to grab the DB service like so:
```
_db = factory.Server.Host.Services.GetService(typeof(ApplicationDbContext)) as ApplicationDbContext;
```
Now you have to:
```
_db = factory.Services.GetService(typeof(ApplicationDbContext)) as  ApplicationDbContext;
```
That causes an error on that line:
```
System.InvalidOperationException : Cannot resolve scoped service 'ApplicationDbContext' from root provider.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback.OnResolve(Type serviceType, IServiceScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at xxxxxxxxxxxTest..ctor(CustomWebApplicationFactory`1 factory) in C:\Users\xxxxxxxx\source\repos\xxxxxxxxx\xxxxxxxxxxxTest.cs:line 21
```
Which can be solved by commenting out in the Startup.cs of the main project:
```
// services.AddDbContext<ApplicationDbContext>();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77889d43-fedb-f8b4-8fea-379ec946555c
* Version Independent ID: f499b131-8b14-7e10-1728-543fdd5a5656
* Content: [Integration tests in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/test/integration-tests.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/test/integration-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by aherrick** [comment]
Using this worked: var db = _factory.Services.CreateScope().ServiceProvider.GetRequiredService<ApplicationDbContext>();

**Comment by Rick-Anderson** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
