### ISSUE TITLE
Confusion about the Key in the Key Ring

### ISSUE THREAD

**Issue by mahendra-gangurde** [aspnet/AspNetCore.Docs#16178]
I got an error like this - 
System.Security.Cryptography.CryptographicException: **The key {e47ceea6-be1f-440b-b204-64ff5a152552} was not found in the key ring.**
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at FIS.Risk.Core.Cryptography.Microsoft.MicrosoftCryptography.Decrypt(String cipherText, EncryptionOption encryptionOptions)
   
   
**So the key referred in the exception above is the same KeyId you get on keyManager.GetAllKeys() result?**

Code sample from documentation -
> // list all keys in the key ring
> var allKeys = keyManager.GetAllKeys();
> Console.WriteLine($"The key ring contains {allKeys.Count} key(s).");
> foreach (var key in allKeys)
> {
> 	Console.WriteLine($"Key {key.KeyId:B}: Created = {key.CreationDate:u}, IsRevoked = {key.IsRevoked}");
> }

**Comment by guardrex** [comment]
Hello @mahendra-gangurde ... It's best if you close this and re-open it from the topic that you're working with (use the **This Page** feedback button+form at the bottom). It will automatically ping the author.

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)
