### ISSUE TITLE
Shift+Alt+D causes InvalidOperationException: Unknown OS platform

### ISSUE THREAD

**Issue by solrevdev** [aspnet/AspNetCore.Docs#16366]
### overview

I was following the procedure part of the [Debug ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.1#procedure) page

![doc-page](https://user-images.githubusercontent.com/374863/71646463-edac2600-2ce0-11ea-8a89-38cfac7535ce.png)

I got this far when I got an exception.

![chrome](https://user-images.githubusercontent.com/374863/71646426-80989080-2ce0-11ea-8c80-f92f33dcb99d.png)

![exception](https://user-images.githubusercontent.com/374863/71646428-855d4480-2ce0-11ea-99f2-25457f53a1d1.png)

### Steps to reproduce

```bash
mkdir -p issue16366
cd issue16366
dotnet new blazorwasm
dotnet run --configuration Debug
``` 
open browser at http://localhost:5000
open dev tools 
console suggests 'Debugging hotkey: Shift+Alt+D (when application has focus)'

Chrome Browser shows this:

```text
An unhandled exception occurred while processing the request.
InvalidOperationException: Unknown OS platform
Microsoft.AspNetCore.Builder.BlazorMonoDebugProxyAppBuilderExtensions.GetLaunchEdgeInstructions(string appRootUrl)

System.InvalidOperationException: Unknown OS platform
   at Microsoft.AspNetCore.Builder.BlazorMonoDebugProxyAppBuilderExtensions.GetLaunchEdgeInstructions(String appRootUrl)
   at Microsoft.AspNetCore.Builder.BlazorMonoDebugProxyAppBuilderExtensions.DebugHome(HttpContext context)
   at Microsoft.AspNetCore.Builder.BlazorMonoDebugProxyAppBuilderExtensions.<>c.<<UseVisualStudioDebuggerConnectionRequestHandlers>b__5_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Console shows this 

```text
 Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/css/bootstrap/bootstrap.min.css.map'. Physical path: '/home/solrevdev/Code/scratch/issue16366/wwwroot/css/bootstrap/bootstrap.min.css.map'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 7.7702ms 200 text/plain
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/_framework/debug?url=http%3A%2F%2Flocalhost%3A5000%2F  
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Unknown OS platform
   at Microsoft.AspNetCore.Builder.BlazorMonoDebugProxyAppBuilderExtensions.GetLaunchEdgeInstructions(String appRootUrl)
   at Microsoft.AspNetCore.Builder.BlazorMonoDebugProxyAppBuilderExtensions.DebugHome(HttpContext context)
   at Microsoft.AspNetCore.Builder.BlazorMonoDebugProxyAppBuilderExtensions.<>c.<<UseVisualStudioDebuggerConnectionRequestHandlers>b__5_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

### My environment

dotnet --info

```bash
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.10
 OS Platform: Linux
 RID:         ubuntu.19.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  157910edee

.NET Core SDKs installed:
  2.1.802 [/usr/share/dotnet/sdk]
  2.2.402 [/usr/share/dotnet/sdk]
  3.0.100 [/usr/share/dotnet/sdk]
  3.1.100 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

```

sreenfetch

```bash

screenfetch -n
 solrevdev@hplaptop
 OS: Ubuntu 19.10 eoan
 Kernel: x86_64 Linux 5.3.0-24-generic
 Uptime: 10d 3h 48m
 Packages: 2435
 Shell: bash 5.0.3
 Resolution: 1920x1080
 DE: GNOME 
 WM: GNOME Shell
 WM Theme: Adwaita
 GTK Theme: Yaru [GTK2/3]
 Icon Theme: Yaru
 Font: Ubuntu 11
 CPU: Intel Core i5-7200U @ 4x 3.1GHz
 GPU: i915drmfb
 RAM: 3796MiB / 7879MiB
```

**Comment by Rick-Anderson** [comment]
Can you create an issue from the doc page? That will connect the doc to the issue. Go to the bottom of the page and select **This page** .

![image](https://user-images.githubusercontent.com/3605364/64829663-24b7c980-d582-11e9-983b-f2a8f4b4df09.png)

**Comment by Rick-Anderson** [comment]
@solrevdev you can edit this issue and copy/paste in the new issue. The images will carry over.

**Comment by guardrex** [comment]
@solrevdev New instructions are in review on https://github.com/aspnet/AspNetCore.Docs/pull/16123. Access the PR diff for the new steps until we get them reviewed and published. If you run into trouble with the new steps, add remarks to the PR.

btw -- I'll add the metadata to your opening comment for tracking purposes.
