### ISSUE TITLE
Add documentation for two [JSInvokable] methods in the same assembly with the same name

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/AspNetCore.Docs#16656]
```
blazor.server.js:8 Uncaught (in promise) Error: System.InvalidOperationException: The assembly '…' contains more than one [JSInvokable] method with identifier 'MyMethodName'. All [JSInvokable] methods within the same assembly must have different identifiers. You can pass a custom identifier as a parameter to the [JSInvokable] attribute.
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.ScanAssemblyForCallableMethods(AssemblyKey assemblyKey)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.GetCachedMethodInfo(AssemblyKey assemblyKey, String methodIdentifier)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(JSRuntime jsRuntime, DotNetInvocationInfo invocationInfo, String argsJson)
    at Object.endInvokeDotNetFromJS (blazor.server.js:8)
    at e.<anonymous> (blazor.server.js:8)
    at blazor.server.js:1
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (blazor.server.js:1)
    at e.processIncomingData (blazor.server.js:1)
    at e.connection.onreceive (blazor.server.js:1)
    at WebSocket.i.onmessage (blazor.server.js:1)
```

As far as I understand, there's an assembly-level namespace where all callable methods have to have unique names/identifiers. The two options are
1) rename the method
2) use the attribute constructor with one parameter to explicitly name the method and use that name from the client-side

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49807900-0d56-e23c-1aef-d79099caeffb
* Version Independent ID: feff434f-912c-0985-d575-4a23a629057d
* Content: [ASP.NET Core Blazor JavaScript interop](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interop?view=aspnetcore-3.1)
* Content Source: [aspnetcore/blazor/javascript-interop.md](https://github.com/aspnet/AspNetCore.Docs/blob/master/aspnetcore/blazor/javascript-interop.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-blazor**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
We currently say ...

> By default, the method identifier is the method name, but you can specify a different identifier using the JSInvokableAttribute constructor.

... but don't provide an example. 🤔 An example would be nice.
